In [ ]:
import numpy as np

In [ ]:
P = np.array([[0.2,0.8],[0.6,0.4]])
print("Transition matrix:\n",P)

Transition matrix:
 [[0.2 0.8]
 [0.6 0.4]]


In [ ]:
S = np.array([0.6,0.4])

In [ ]:
for i in range(10):
    S = np.dot(S,P)
    print("\nIteration {0}. Probability vector S = {1}". format(i,S))

print("\nFinal probability vector = ",S)


Iteration 0. Probability vector S = [0.36 0.64]

Iteration 1. Probability vector S = [0.456 0.544]

Iteration 2. Probability vector S = [0.4176 0.5824]

Iteration 3. Probability vector S = [0.43296 0.56704]

Iteration 4. Probability vector S = [0.426816 0.573184]

Iteration 5. Probability vector S = [0.4292736 0.5707264]

Iteration 6. Probability vector S = [0.42829056 0.57170944]

Iteration 7. Probability vector S = [0.42868378 0.57131622]

Iteration 8. Probability vector S = [0.42852649 0.57147351]

Iteration 9. Probability vector S = [0.4285894 0.5714106]

Final probability vector =  [0.4285894 0.5714106]


Problem 2


In [ ]:
from sympy import symbols, Eq, solve

In [ ]:
T = np.array
 ([[0.3,0.2,0.5],[0.4,0,0],[0.1,0,0.9]])
print("Transition matrix:\n",T)

Transition matrix:
 [[0.3 0.2 0.5]
 [0.4 0.  0. ]
 [0.1 0.  0.9]]


In [ ]:
R = np.array([[-3,-2,0,0],[-2,0,0,10],[-3,0,0,0],[0,0,0,0]])
print("Reward matrix:\n",R)

Reward matrix:
 [[-3 -2  0  0]
 [-2  0  0 10]
 [-3  0  0  0]
 [ 0  0  0  0]]


In [ ]:
x,y,z = symbols("x,y,z")

In [ ]:
initial_state = np.array([x,y,z])

In [ ]:
initial_equation = np.dot(initial_state,T)
print(initial_equation)

[0.3*x + 0.4*y + 0.1*z 0.2*x 0.5*x + 0.9*z]


In [ ]:
initial_equation[1]

0.2*x

In [ ]:
eq1 = Eq(initial_equation[0], x)
eq1

Eq(0.3*x + 0.4*y + 0.1*z, x)

In [ ]:
eq2 = Eq(initial_equation[1], y)
eq2

Eq(0.2*x, y)

In [ ]:
eq3 = Eq(initial_equation[2], z)
eq3

Eq(0.5*x + 0.9*z, z)

In [ ]:
eq4 = Eq((x+y+z), 1)
eq4

Eq(x + y + z, 1)

In [ ]:
solutions = solve([eq1, eq2, eq3, eq4], (x, y, z, 1))
solutions

[(0.330515864914088,
  -0.361031729828177,
  -0.152579324570442,
  -0.183095189484530),
 (0.0, 0.0, 0.0, 0.0),
 (0.800000000000000, 0.400000000000000, -0.800000000000000, 0.400000000000000),
 (0.136150801752578, 0.0276983964948434, 0.819245991237108, 0.983095189484530)]

In [ ]:
print("solutions", [solutions[i][:3] for i in range(len(solutions))])

solutions [(0.330515864914088, -0.361031729828177, -0.152579324570442), (0.0, 0.0, 0.0), (0.800000000000000, 0.400000000000000, -0.800000000000000), (0.136150801752578, 0.0276983964948434, 0.819245991237108)]


In [ ]:
print("solutions", [solutions[0][:3]])

solutions [(0.330515864914088, -0.361031729828177, -0.152579324570442)]


In [ ]:
print("solutions", [solutions[1][:3]])

solutions [(0.0, 0.0, 0.0)]


In [ ]:
print("solutions", [solutions[2][:3]])

solutions [(0.800000000000000, 0.400000000000000, -0.800000000000000)]
